# Generated by Django 5.1 on 2025-04-13 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MPic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pic', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'm_pic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TMatlevIndicator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pillar', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('indicator', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 't_matlev_indicator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TMatlevKriteria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('kriteria', models.TextField(blank=True, null=True)),
                ('max_level', models.IntegerField(blank=True, default=3, null=True)),
                ('level_get', models.IntegerField(blank=True, default=0, null=True)),
                ('level_weight', models.IntegerField(blank=True, default=0, null=True)),
                ('level_sum', models.IntegerField(blank=True, default=0, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevindicator')),
            ],
            options={
                'db_table': 't_matlev_kriteria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TMatlevKriteriaDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maturity', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('kriteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevkriteria')),
            ],
            options={
                'db_table': 't_matlev_kriteria_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TMatlevKriteriaColumn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('column_name', models.TextField(blank=True, null=True)),
                ('column_type', models.CharField(blank=True, max_length=30, null=True)),
                ('maturity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevkriteriadetail')),
            ],
            options={
                'db_table': 't_matlev_kriteria_column',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TMatlevKriteriaPic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maturity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevkriteriadetail')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mpic')),
            ],
            options={
                'db_table': 't_matlev_kriteria_pic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TRMatlev',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevindicator')),
                ('kriteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevkriteria')),
                ('maturity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevkriteriadetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tr_matlev',
                'managed': True,
            },
        ),
    ]
