# Generated by Django 5.1 on 2025-04-13 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMatlevKriteriaColumnOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.TextField(blank=True, null=True)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevkriteriacolumn')),
            ],
            options={
                'db_table': 't_matlev_kriteria_column_option',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TRMatlevColumn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevkriteriacolumn')),
                ('matlev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.trmatlev')),
            ],
            options={
                'db_table': 'tr_matlev_column',
                'managed': True,
            },
        ),
    ]
