# Generated by Django 5.1 on 2025-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mpic_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpic',
            name='pic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
