# Generated by Django 5.1 on 2025-04-29 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mpic_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmatlevkriteriacolumn',
            name='hints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmatlevkriteriacolumn',
            name='sub_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevkriteriacolumn'),
        ),
    ]
