# Generated by Django 5.1 on 2025-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tmatlevkriteriacolumn_hints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmatlevkriteriacolumn',
            name='show_table',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
