# Generated by Django 5.1 on 2025-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tmatlevkriteriacolumn_show_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmatlevkriteriacolumn',
            name='show_table',
            field=models.BooleanField(default=False),
        ),
    ]
