# Generated by Django 5.1 on 2025-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tmatlevkriteriacolumn_show_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='trmatlevcolumn',
            name='value_files',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/'),
        ),
    ]
