# Generated by Django 5.1 on 2025-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_trmatlevcolumn_value_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmatlevkriteriacolumn',
            name='equation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
