# Generated by Django 5.1 on 2025-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tmatlevkriteriacolumn_equation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmatlevkriteriacolumn',
            name='negative_input',
            field=models.BooleanField(default=False),
        ),
    ]
