# Generated by Django 5.1 on 2025-07-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tmatlevkriteriacolumn_negative_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmatlevkriteriadetail',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
