# Generated by Django 5.1 on 2025-07-02 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='trmatlev',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
