# Generated by Django 5.1 on 2025-07-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_trmatlev_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmatlevkriteriadetail',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
