# Generated by Django 5.1 on 2025-07-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tmatlevkriteriadetail_last_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmatlevkriteriadetail',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
