# Generated by Django 5.1 on 2025-07-06 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_tmatlevkriteriadetail_keterangan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('activity_type', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('DOWNLOAD', 'Download')], max_length=20, verbose_name='Activity Type')),
                ('app', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('DATA', 'Data'), ('MASTER', 'Master'), ('OTHER', 'Other')], max_length=20, verbose_name='Application')),
                ('path', models.CharField(max_length=255, verbose_name='URL Path')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP Method')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Additional Data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='main_activi_timesta_c39e8d_idx'), models.Index(fields=['user'], name='main_activi_user_id_3c7ce6_idx'), models.Index(fields=['app'], name='main_activi_app_5ea2d3_idx')],
            },
        ),
    ]
