# Generated by Django 5.1 on 2025-11-27 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('long', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_detail',
                'managed': True,
            },
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='t_activity__timesta_8f33fb_idx',
            old_name='main_activi_timesta_c39e8d_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='t_activity__user_id_3338e4_idx',
            old_name='main_activi_user_id_3c7ce6_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='t_activity__app_75a838_idx',
            old_name='main_activi_app_5ea2d3_idx',
        ),
        migrations.AlterField(
            model_name='userpic',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userpic',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mpic'),
        ),
        migrations.AlterField(
            model_name='userpic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table='t_activity_logs',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
