# Generated by Django 5.1 on 2025-11-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_userdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='role',
            field=models.CharField(blank=True, default='contributor', max_length=100, null=True),
        ),
    ]
