# Generated by Django 5.1 on 2025-12-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_userdetail_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'm_group',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mgroup'),
        ),
    ]
