# Generated by Django 5.1 on 2025-12-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_mgroup_alter_userdetail_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgroup',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mpic'),
        ),
    ]
