# Generated by Django 5.1 on 2025-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_mgroup_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgroup',
            name='group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
