# Generated by Django 5.1 on 2025-12-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_mgroup_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='long',
        ),
        migrations.CreateModel(
            name='MLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('long', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mgroup')),
            ],
            options={
                'db_table': 'm_location',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='userdetail',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mlocation'),
        ),
    ]
