# Generated by Django 5.1 on 2025-12-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_userdetail_group_remove_userdetail_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlocation',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mpic'),
        ),
    ]
