# Generated by Django 5.1 on 2025-12-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_tremission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tremission',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mlocation'),
        ),
    ]
