# Generated by Django 5.0.14 on 2026-01-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_tremission_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmatlevkriteriacolumn',
            name='emition_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
