# Generated by Django 5.0.14 on 2026-01-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_tmatlevkriteriacolumn_emition_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmatlevkriteriacolumn',
            old_name='emition_category',
            new_name='emission_category',
        ),
    ]
