# Generated by Django 5.0.14 on 2026-01-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_emition_category_tmatlevkriteriacolumn_emission_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlocation',
            name='banjir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mlocation',
            name='cuacaEkstrim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mlocation',
            name='kekeringan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mlocation',
            name='longsor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
