# Generated by Django 5.0.14 on 2026-01-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_mlocation_banjir_mlocation_cuacaekstrim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpic',
            name='pic_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
