# Generated by Django 5.0.14 on 2026-01-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_mpic_pic_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='trmatlev',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mpic'),
        ),
    ]
