# Generated by Django 5.0.14 on 2026-01-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_trmatlev_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMatlevKriteriaLevelGet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level_get', models.IntegerField(blank=True, default=0, null=True)),
                ('kriteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tmatlevkriteria')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mpic')),
            ],
            options={
                'db_table': 't_matlev_kriteria_levelget',
                'managed': True,
            },
        ),
    ]
